# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.IntegerField(auto_created=1000, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('balance', models.IntegerField()),
            ],
        ),
        #migrations.DeleteModel(
        #    name='saying',
        #),
    ]
