# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_auto_20171208_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.IntegerField(default=1001, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
