# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0004_auto_20171209_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=10),
        ),
    ]
