# Generated by Django 2.0 on 2017-12-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0009_auto_20171221_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=1001, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
